name: build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1

      - name: Build
        run: |
          ./gradlew build
          mkdir -p release
          cp $(find ./build/libs -maxdepth 1 -type f -name "*.jar") ./release/

      - uses: actions/upload-artifact@v4
        with:
          name: opus4j-java
          path: ./release/
